# Generated by Django 4.2 on 2023-04-15 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_currency_code_alter_payment_reference_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
